public class CallHistoryData {
    @auraenabled
    public String callStartedOn;
    
    @auraenabled
    public String callDate;
    
    @auraenabled
    public String uniqueIdentifier;
    
    @auraenabled
    public String source;
    
    @auraenabled
    public String destination;
    
    @auraenabled
    public String duration;
    
    @auraenabled
    public String callRecordingURL;
    
    @auraenabled
    public String callStatus;
}